<a href="https://colab.research.google.com/github/mjellmabejta/webscraper/blob/main/webscrapingfinalexamMJELLMABEJTA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [58]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [59]:
URL = "https://www.goodreads.com/list/show/79160"
page = requests.get(URL)
#page.status_code

#print(page.text)

In [60]:
soup = BeautifulSoup(page.content, "html.parser")

In [61]:
booktitle = []
for item in soup.find_all('span', itemprop="name", role="heading"):
  booktitle.append(item.get_text())

booktitle

['The Girl with the Dragon Tattoo (Millennium, #1)',
 'And Then There Were None',
 'Gone Girl',
 'The Da Vinci Code (Robert Langdon, #2)',
 'Murder on the Orient Express (Hercule Poirot, #9)',
 'Rebecca',
 'The Name of the Rose',
 "The Girl Who Kicked the Hornet's Nest (Millennium, #3)",
 'Angels & Demons (Robert Langdon, #1)',
 'The Curious Incident of the Dog in the Night-Time',
 'The Girl Who Played with Fire (Millennium, #2)',
 'The Shadow of the Wind (The Cemetery of Forgotten Books, #1)',
 'The Complete Sherlock Holmes',
 'The Murder of Roger Ackroyd (Hercule Poirot, #3)',
 'A Study in Scarlet (Sherlock Holmes, #1)',
 'The Hound of the Baskervilles (Sherlock Holmes, #5)',
 'Perfume: The Story of a Murderer',
 'Murder at the Vicarage',
 'The Thirteenth Tale',
 'The Lost Symbol (Robert Langdon, #3)',
 'The Firm',
 'In Cold Blood',
 'The Godfather (The Godfather, #1)',
 'Inferno (Robert Langdon, #4)',
 'Sharp Objects',
 'The Adventures of Sherlock Holmes (Sherlock Holmes, #3)',
 'The Alienist (Dr. Laszlo Kreizler, #1)',
 'Dr. Jekyll and Mr. Hyde',
 'The Mysterious Affair at Styles (Hercule Poirot, #1)',
 'Misery',
 'Midnight in the Garden of Good and Evil',
 'Death on the Nile (Hercule Poirot, #16)',
 '11/22/63',
 'One for the Money (Stephanie Plum, #1)',
 'Eye of the Needle',
 'The Pillars of the Earth (Kingsbridge, #1)',
 'Dark Places',
 'The Sign of Four (Sherlock Holmes, #2)',
 'Snow Falling on Cedars',
 'In the Woods (Dublin Murder Squad, #1)',
 'The Sweetness at the Bottom of the Pie (Flavia de Luce, #1)',
 'The Lovely Bones',
 'The Bone Collector (Lincoln Rhyme, #1)',
 'The Pelican Brief',
 'Presumed Innocent (Kindle County Legal Thriller, #1)',
 'The Historian',
 "The No. 1 Ladies' Detective Agency (No. 1 Ladies' Detective Agency, #1)",
 'Crime and Punishment',
 'The Big Sleep (Philip Marlowe, #1)',
 'Still Life (Chief Inspector Armand Gamache, #1)',
 "The Cuckoo's Calling (Cormoran Strike, #1)",
 'Killing Floor (Jack Reacher, #1)',
 'The Woman in White',
 'To Kill a Mockingbird',
 'A is for Alibi (Kinsey Millhone, #1)',
 'Shutter Island',
 'The Complete Stories and Poems',
 'A Time to Kill (Jake Brigance, #1)',
 'Before I Go to Sleep',
 'The Girl on the Train',
 'The Maltese Falcon',
 'The Lincoln Lawyer (Mickey Haller, #1; Harry Bosch Universe, #15)',
 'A Scandal in Bohemia (The Adventures of Sherlock Holmes, #1)',
 'The Secret History',
 'Postmortem (Kay Scarpetta, #1)',
 'Atonement',
 "Sarah's Key",
 'The Eyre Affair (Thursday Next, #1)',
 'Naked in Death (In Death, #1)',
 'The Complete Sherlock Holmes: Volume II',
 'Mystic River',
 'The A.B.C. Murders (Hercule Poirot, #12)',
 'The Moonstone',
 "The Beekeeper's Apprentice (Mary Russell and Sherlock Holmes, #1)",
 'Red Dragon (Hannibal Lecter, #1)',
 'The Black Echo (Harry Bosch Universe, #1)',
 'The Brothers Karamazov',
 'The Snowman (Harry Hole, #7)',
 'The Black Dahlia (L.A. Quartet, #1)',
 'Tripwire  (Jack Reacher, #3)',
 'The Blind Assassin',
 'The Secret Keeper',
 'The Man in the Brown Suit (Colonel Race, #1)',
 'The Likeness (Dublin Murder Squad, #2)',
 'Tinker, Tailor, Soldier, Spy (George Smiley, #5; Karla Trilogy, #1)',
 'Hard Eight (Stephanie Plum, #8)',
 'Rules of Prey (Lucas Davenport, #1)',
 'State of Wonder',
 'The Poet (Jack McEvoy, #1; Harry Bosch Universe, #5)',
 'The Secret of the Old Clock (Nancy Drew Mystery Stories, #1)',
 'Gone Tomorrow (Jack Reacher, #13)',
 'Alias Grace',
 'The Westing Game',
 'Ten Big Ones (Stephanie Plum, #10)',
 'Twelve Sharp (Stephanie Plum, #12)',
 'The Forgotten Garden',
 'Running Blind (Jack Reacher, #4)',
 'The Body in the Library',
 'Fearless Fourteen (Stephanie Plum, #14)',
 'The House at Riverton']

In [62]:
author = []
for item in soup.find_all('a', {'class' : 'authorName'}):
  author.append(item.get_text())

author

['Stieg Larsson',
 'Agatha Christie',
 'Gillian Flynn',
 'Dan Brown',
 'Agatha Christie',
 'Daphne du Maurier',
 'Umberto Eco',
 'Stieg Larsson',
 'Dan Brown',
 'Mark Haddon',
 'Stieg Larsson',
 'Carlos Ruiz Zafón',
 'Arthur Conan Doyle',
 'Agatha Christie',
 'Arthur Conan Doyle',
 'Arthur Conan Doyle',
 'Patrick Süskind',
 'Agatha Christie',
 'Diane Setterfield',
 'Dan Brown',
 'Robin Waterfield',
 'Truman Capote',
 'Mario Puzo',
 'Dan Brown',
 'Gillian Flynn',
 'Arthur Conan Doyle',
 'Caleb Carr',
 'Robert Louis Stevenson',
 'Agatha Christie',
 'Stephen King',
 'John Berendt',
 'Agatha Christie',
 'Stephen King',
 'Janet Evanovich',
 'Ken Follett',
 'Ken Follett',
 'Gillian Flynn',
 'Arthur Conan Doyle',
 'David Guterson',
 'Tana French',
 'Alan Bradley',
 'Alice Sebold',
 'Jeffery Deaver',
 'John Grisham',
 'Scott Turow',
 'Elizabeth Kostova',
 'Alexander McCall Smith',
 'Fyodor Dostoevsky',
 'Raymond Chandler',
 'Louise Penny',
 'Robert Galbraith',
 'Lee Child',
 'Wilkie Collins',
 'Harper Lee',
 'Sue Grafton',
 'Dennis Lehane',
 'Edgar Allan Poe',
 'John Grisham',
 'S.J. Watson',
 'Paula Hawkins',
 'Dashiell Hammett',
 'Michael Connelly',
 'Ronald  Holt',
 'Donna Tartt',
 'Patricia Cornwell',
 'Ian McEwan',
 'Tatiana de Rosnay',
 'Jasper Fforde',
 'J.D. Robb',
 'Arthur Conan Doyle',
 'Dennis Lehane',
 'Agatha Christie',
 'Wilkie Collins',
 'Laurie R. King',
 'Thomas  Harris',
 'Michael Connelly',
 'Fyodor Dostoevsky',
 'Jo Nesbø',
 'James Ellroy',
 'Lee Child',
 'Margaret Atwood',
 'Kate Morton',
 'Agatha Christie',
 'Tana French',
 'John le Carré',
 'Janet Evanovich',
 'John Sandford',
 'Ann Patchett',
 'Michael Connelly',
 'Carolyn Keene',
 'Lee Child',
 'Margaret Atwood',
 'Ellen Raskin',
 'Janet Evanovich',
 'Janet Evanovich',
 'Kate Morton',
 'Lee Child',
 'Agatha Christie',
 'Janet Evanovich',
 'Kate Morton']

In [63]:
avg_rating = []
for item in soup.find_all('span', {'class' : 'minirating'}):
  avg_rating.append(item.get_text())

avg_rating

[' 4.16 avg rating — 2,999,101 ratings',
 ' 4.28 avg rating — 1,172,519 ratings',
 ' 4.12 avg rating — 2,820,375 ratings',
 ' 3.90 avg rating — 2,220,710 ratings',
 ' 4.20 avg rating — 538,522 ratings',
 ' 4.24 avg rating — 571,337 ratings',
 ' 4.13 avg rating — 343,291 ratings',
 ' 4.23 avg rating — 705,362 ratings',
 ' 3.93 avg rating — 3,041,556 ratings',
 ' 3.89 avg rating — 1,393,344 ratings',
 ' 4.25 avg rating — 884,635 ratings',
 ' 4.29 avg rating — 577,193 ratings',
 ' 4.50 avg rating — 192,211 ratings',
 ' 4.26 avg rating — 228,156 ratings',
 ' 4.14 avg rating — 405,987 ratings',
 ' 4.13 avg rating — 317,172 ratings',
 ' 4.04 avg rating — 414,929 ratings',
 ' 4.06 avg rating — 175,390 ratings',
 ' 3.97 avg rating — 302,152 ratings',
 ' 3.74 avg rating — 581,253 ratings',
 ' 4.05 avg rating — 608,409 ratings',
 ' 4.08 avg rating — 612,753 ratings',
 ' 4.38 avg rating — 391,029 ratings',
 ' 3.88 avg rating — 525,472 ratings',
 ' 4.01 avg rating — 899,832 ratings',
 ' 4.30 avg rating — 280,868 ratings',
 ' 4.06 avg rating — 166,680 ratings',
 ' 3.83 avg rating — 508,973 ratings',
 'really liked it 4.00 avg rating — 363,930 ratings',
 ' 4.20 avg rating — 622,157 ratings',
 ' 3.92 avg rating — 253,849 ratings',
 ' 4.12 avg rating — 221,907 ratings',
 ' 4.32 avg rating — 493,695 ratings',
 ' 4.04 avg rating — 526,138 ratings',
 ' 4.20 avg rating — 147,571 ratings',
 ' 4.33 avg rating — 723,064 ratings',
 ' 3.95 avg rating — 687,900 ratings',
 ' 3.91 avg rating — 141,497 ratings',
 ' 3.85 avg rating — 180,487 ratings',
 ' 3.78 avg rating — 371,254 ratings',
 ' 3.82 avg rating — 161,432 ratings',
 ' 3.84 avg rating — 2,245,826 ratings',
 ' 4.20 avg rating — 173,910 ratings',
 ' 4.04 avg rating — 414,687 ratings',
 ' 4.10 avg rating — 113,132 ratings',
 ' 3.79 avg rating — 257,579 ratings',
 ' 3.80 avg rating — 255,392 ratings',
 ' 4.25 avg rating — 798,073 ratings',
 ' 3.96 avg rating — 146,083 ratings',
 ' 3.90 avg rating — 214,596 ratings',
 ' 3.88 avg rating — 545,984 ratings',
 ' 4.07 avg rating — 295,559 ratings',
 'really liked it 4.00 avg rating — 145,983 ratings',
 ' 4.27 avg rating — 5,584,470 ratings',
 ' 3.86 avg rating — 177,396 ratings',
 ' 4.10 avg rating — 182,922 ratings',
 ' 4.38 avg rating — 242,942 ratings',
 ' 4.10 avg rating — 777,655 ratings',
 ' 3.90 avg rating — 323,058 ratings',
 ' 3.95 avg rating — 2,671,936 ratings',
 ' 3.89 avg rating — 100,492 ratings',
 ' 4.19 avg rating — 220,664 ratings',
 ' 4.23 avg rating — 85,180 ratings',
 ' 4.17 avg rating — 532,598 ratings',
 ' 4.03 avg rating — 231,345 ratings',
 ' 3.93 avg rating — 492,112 ratings',
 ' 4.17 avg rating — 458,615 ratings',
 ' 3.88 avg rating — 128,858 ratings',
 ' 4.13 avg rating — 183,022 ratings',
 ' 4.48 avg rating — 79,806 ratings',
 ' 4.16 avg rating — 138,495 ratings',
 ' 4.03 avg rating — 142,588 ratings',
 ' 3.91 avg rating — 88,706 ratings',
 ' 4.05 avg rating — 79,336 ratings',
 ' 4.05 avg rating — 312,594 ratings',
 ' 4.12 avg rating — 183,388 ratings',
 ' 4.35 avg rating — 293,754 ratings',
 ' 4.02 avg rating — 128,853 ratings',
 ' 3.77 avg rating — 88,112 ratings',
 ' 4.11 avg rating — 113,276 ratings',
 ' 3.96 avg rating — 149,335 ratings',
 ' 4.15 avg rating — 151,924 ratings',
 ' 3.96 avg rating — 102,914 ratings',
 ' 4.06 avg rating — 151,430 ratings',
 ' 4.05 avg rating — 87,844 ratings',
 ' 4.16 avg rating — 121,055 ratings',
 ' 4.11 avg rating — 82,381 ratings',
 ' 3.89 avg rating — 179,413 ratings',
 ' 4.22 avg rating — 94,617 ratings',
 ' 3.98 avg rating — 75,333 ratings',
 ' 4.18 avg rating — 98,706 ratings',
 ' 4.04 avg rating — 133,433 ratings',
 ' 4.01 avg rating — 197,050 ratings',
 ' 4.15 avg rating — 98,712 ratings',
 ' 4.16 avg rating — 96,205 ratings',
 ' 4.14 avg rating — 212,017 ratings',
 ' 4.12 avg rating — 98,048 ratings',
 ' 3.84 avg rating — 91,706 ratings',
 ' 4.04 avg rating — 90,845 ratings',
 ' 3.95 avg rating — 112,321 ratings']

In [76]:
ratings = []
for i in range (len(avg_rating)):
  num = re.sub('\D', '', avg_rating[i])[:3]
  rating = num[0] + '.' + num[1:] 
  ratings.append(rating)

ratings

['4.16',
 '4.28',
 '4.12',
 '3.90',
 '4.20',
 '4.24',
 '4.13',
 '4.23',
 '3.93',
 '3.89',
 '4.25',
 '4.29',
 '4.50',
 '4.26',
 '4.14',
 '4.13',
 '4.04',
 '4.06',
 '3.97',
 '3.74',
 '4.05',
 '4.08',
 '4.38',
 '3.88',
 '4.01',
 '4.30',
 '4.06',
 '3.83',
 '4.00',
 '4.20',
 '3.92',
 '4.12',
 '4.32',
 '4.04',
 '4.20',
 '4.33',
 '3.95',
 '3.91',
 '3.85',
 '3.78',
 '3.82',
 '3.84',
 '4.20',
 '4.04',
 '4.10',
 '3.79',
 '3.80',
 '4.25',
 '3.96',
 '3.90',
 '3.88',
 '4.07',
 '4.00',
 '4.27',
 '3.86',
 '4.10',
 '4.38',
 '4.10',
 '3.90',
 '3.95',
 '3.89',
 '4.19',
 '4.23',
 '4.17',
 '4.03',
 '3.93',
 '4.17',
 '3.88',
 '4.13',
 '4.48',
 '4.16',
 '4.03',
 '3.91',
 '4.05',
 '4.05',
 '4.12',
 '4.35',
 '4.02',
 '3.77',
 '4.11',
 '3.96',
 '4.15',
 '3.96',
 '4.06',
 '4.05',
 '4.16',
 '4.11',
 '3.89',
 '4.22',
 '3.98',
 '4.18',
 '4.04',
 '4.01',
 '4.15',
 '4.16',
 '4.14',
 '4.12',
 '3.84',
 '4.04',
 '3.95']

In [80]:
data = pd.DataFrame()

data['Book Title'] = booktitle
data['Author'] = author
data['Average Rating'] = ratings

data

,Book Title,Author,Average Rating
0,"The Girl with the Dragon Tattoo (Millennium, #1)",Stieg Larsson,4.16
1,And Then There Were None,Agatha Christie,4.28
2,Gone Girl,Gillian Flynn,4.12
3,"The Da Vinci Code (Robert Langdon, #2)",Dan Brown,3.90
4,"Murder on the Orient Express (Hercule Poirot, #9)",Agatha Christie,4.20
...,...,...,...
95,The Forgotten Garden,Kate Morton,4.14
96,"Running Blind (Jack Reacher, #4)",Lee Child,4.12
97,The Body in the Library,Agatha Christie,3.84
98,"Fearless Fourteen (Stephanie Plum, #14)",Janet Evanovich,4.04
99,The House at Riverton,Kate Morton,3.95

In [81]:
data.to_csv('MostPopularMysteriesonGoodreads.csv', index=False)